extension PolicyReasonCatalog {
    private static let cloudAndContainerCredentialCommandFamily = CommandFamily([
        "read local cloud and container credential files",
        "cat ~/.aws/credentials",
        "less ~/.aws/credentials",
        "head ~/.aws/credentials",
        "tail ~/.aws/credentials",
        "grep <pattern> ~/.aws/credentials",
        "rg <pattern> ~/.aws/credentials",
        "base64 ~/.aws/credentials",
        "xxd ~/.aws/credentials",
        "strings ~/.aws/credentials",
        "open ~/.aws/credentials",
        "cp ~/.aws/credentials <destination>",
        "rsync ~/.aws/credentials <destination>",
        "curl -F file=@~/.aws/credentials <url>",
        "curl --data-binary @~/.aws/credentials <url>",
        "tar -czf <archive> ~/.aws/credentials",
        "zip -r <archive> ~/.aws/credentials",
        "cat ~/.aws/config",
        "open ~/.aws/config",
        "cp ~/.aws/config <destination>",
        "aws configure get aws_access_key_id",
        "aws configure get aws_secret_access_key",
        "aws configure get aws_session_token",
        "aws configure export-credentials",
        "aws configure export-credentials --format env",
        "aws sso get-role-credentials",
        "aws sso login",
        "aws sso logout",
        "aws ecr get-login-password",
        "aws codeartifact get-authorization-token",
        "cat ~/.config/gcloud/application_default_credentials.json",
        "open ~/.config/gcloud/application_default_credentials.json",
        "cp ~/.config/gcloud/application_default_credentials.json <destination>",
        "curl -F file=@~/.config/gcloud/application_default_credentials.json <url>",
        "gcloud auth print-access-token",
        "gcloud auth print-identity-token",
        "gcloud auth application-default print-access-token",
        "gcloud auth login",
        "gcloud auth revoke",
        "gcloud auth application-default login",
        "gcloud auth application-default revoke",
        "gcloud auth configure-docker",
        "gcloud config config-helper --format=json",
        "cat ~/.docker/config.json",
        "open ~/.docker/config.json",
        "cp ~/.docker/config.json <destination>",
        "curl -F file=@~/.docker/config.json <url>",
        "docker login",
        "docker logout",
        "docker context export",
        "cat ~/.kube/config",
        "open ~/.kube/config",
        "cp ~/.kube/config <destination>",
        "curl -F file=@~/.kube/config <url>",
        "tar -czf <archive> ~/.kube/config",
        "zip -r <archive> ~/.kube/config",
        "kubectl config view --raw",
        "kubectl config view --flatten --raw",
        "kubectl config view --minify --raw",
        "kubectl config set-credentials",
        "kubectl config unset",
        "kubectl config delete-user",
        "kubectl create token",
    ])
    static let cloudAndContainerCredentialCommands = cloudAndContainerCredentialCommandFamily.commands

    static func isCloudAndContainerCredentialCommand(_ command: String) -> Bool {
        cloudAndContainerCredentialCommandFamily.contains(command)
    }
}
