extension PolicyReasonCatalog {
    static let catalogCommandFamilies: [(name: String, commands: [String])] = [
        ("baselineAskFirstCommands", baselineAskFirstCommands),
        ("baselineForbiddenCommands", baselineForbiddenCommands),
        ("homebrewPackageManagerReviewCommands", homebrewPackageManagerReviewCommands),
        ("pipDependencyMutationCommands", pipDependencyMutationCommands),
        ("pipPackageFetchAndCacheCommands", pipPackageFetchAndCacheCommands),
        ("pipCacheMutationCommands", pipCacheMutationCommands),
        ("pipAskFirstCommands", pipAskFirstCommands),
        ("uvDependencyMutationCommands", uvDependencyMutationCommands),
        ("npmDependencyMutationCommands", npmDependencyMutationCommands),
        ("pnpmDependencyMutationCommands", pnpmDependencyMutationCommands),
        ("yarnDependencyMutationCommands", yarnDependencyMutationCommands),
        ("bunDependencyMutationCommands", bunDependencyMutationCommands),
        ("npmEphemeralPackageExecutionCommands", npmEphemeralPackageExecutionCommands),
        ("pnpmEphemeralPackageExecutionCommands", pnpmEphemeralPackageExecutionCommands),
        ("yarnEphemeralPackageExecutionCommands", yarnEphemeralPackageExecutionCommands),
        ("bunEphemeralPackageExecutionCommands", bunEphemeralPackageExecutionCommands),
        ("pythonEphemeralPackageExecutionCommands", pythonEphemeralPackageExecutionCommands),
        ("ephemeralPackageExecutionCommands", ephemeralPackageExecutionCommands),
        ("packageRegistryMutationCommands", packageRegistryMutationCommands),
        ("corepackPackageManagerActivationCommands", corepackPackageManagerActivationCommands),
        ("rubyBundlerDependencyMutationCommands", rubyBundlerDependencyMutationCommands),
        ("swiftPackageDependencyResolutionCommands", swiftPackageDependencyResolutionCommands),
        ("goDependencyMutationCommands", goDependencyMutationCommands),
        ("cargoDependencyMutationCommands", cargoDependencyMutationCommands),
        ("cocoapodsDependencyMutationCommands", cocoapodsDependencyMutationCommands),
        ("carthageDependencyMutationCommands", carthageDependencyMutationCommands),
        ("xcodebuildProjectMutationCommands", xcodebuildProjectMutationCommands),
        ("virtualEnvironmentMutationCommands", virtualEnvironmentMutationCommands),
        ("baselineLockfileMutationCommands", baselineLockfileMutationCommands),
        ("versionManagerMutationCommands", versionManagerMutationCommands),
        ("localGitWorkspaceMutationCommands", localGitWorkspaceMutationCommands),
        ("gitHubCliMutationCommands", gitHubCliMutationCommands),
        ("workspaceMutationCommands", workspaceMutationCommands),
        ("secretBearingBroadSearchCommands", secretBearingBroadSearchCommands),
    ] + baselineAskFirstCommandFamilies
        + baselineForbiddenCommandFamilies
}
